[package]
name = "rapier_projects"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy_rapier3d = { version = "0.32.0", features = [ "simd-stable", "debug-render-3d" ] }
rapier3d = {version = "0.31.0", features = ["simd-stable"]}

